image: maven:3-jdk-11
stages:
  - Test
  - Build-jar


Unit-tests:
  stage: Test
  needs: []
  script:
    - mvn verify
  artifacts:
    when: always

Build-jar:
  stage: Build-jar
  needs:
    - Unit-tests
  script: "mvn clean package -B -DskipTests"
  artifacts:
    paths:
      - target/payment-0.0.1-SNAPSHOT.jar
  only:
    - master